LIKELION-FE-LAB9/Market-Karly

- client/html/register.html
TopBanner, Header, main, Footer 
회원가입 폼을 처음 마크업 해봐서 어려웠습니다.
8시간,,,?
최대한 웹 접근성과 BEM방식 회원가입 폼을 처음 마크업 해봐서 어려웠습니다.
> [#33, #35, #36, #37] Register Markup 완료

- client/html/main.html
swiper.css 주석 해제
스와이퍼에 주석이 되어있어서 적용이 안되었던 문제 해결
10초
> [#136] swiper.css 주석 해제

- client/css/pages/product-detail.css
- client/html/product-detail.html
product-detail html, css 화면 깨짐 수정
-css 파일의 '그러니'삭제
-html 중복 코드 삭제
-문의하기 버튼의 글자 스타일 추가
30분
git 이력 관리가 어렵다는 생각이 들었습니다.
> [#99] product-detail html, css 화면 깨짐 수정

- client/css/pages/product-detail.css
- client/html/product-detail.html
Reverts LIKELION-FE-LAB9/Market-Karly#139
> Revert "[#99] product-detail html, css 화면 깨짐 수정"

- client/css/pages/login.css
- client/html/login.html
css 코드 수정 및 회원가입 링크 추가
css 수정 및 회원가입 링크 추가
클래스 이름 변경, 회원가입 버튼 클릭시 회원가입 연결
30분
> [#109] login 리팩토링

- client/css/pages/login.css
- client/html/login.html
- client/js/product_list/ukss.js
초기화 버튼을 눌러도 체크 수량이 초기화 되지 않아 이를 수정하였다.
리셋 함수에 해당 좌표를 잡아 이를 실행하면 빈값으로 초기화 되어 보이는 효과 생성
5분
X
> [#150] Product-List | 초기화 버튼 에러 문제 해결

- client/css/pages/login.css
- client/html/login-popup.html
- client/html/login.html
- client/js/login/jm.js
로그인 버튼 클릭 시 팝업창 구현 완료
로그인 버튼 클릭시 아이디, 비밀번호를 확인하세요 메세지 출력, 확인버튼 누르면 팝업창 닫힘
크롬은 주소창 제거가 불가하다해서 주소창이 뜨네요..
8시간
기초 강의듣기
> [#147] 로그인 버튼 클릭 시 팝업 창 구현

- client/css/pages/register.css
- client/html/register.html
- client/js/register/woonki.js
- 아이디 6자리 이하일때 에러메시지 나오게 하기
- 조건에 맞지 않느다면 버튼 비활성화
- 조건에 맞다면 에러메시지 안나오게 하고 버튼 활성화 하기 완성
키 입력 하나하나 조건을 비교하여 에러메시지가 나오게 하였습니다.
2월6일 ~ 7일 오전 10시
input value에 값을 넣는것이 어려웠습니다. 또한 그걸 조건을 어떻게 줘야하는지 헷갈렸습니다.
> #53 회원가입_아이디 유효성 검사 및 중복확인 버튼 구현

- client/assets/icons/Icon/up.svg
- client/assets/icons/Icon/x.svg
- client/css/pages/cart.css
- client/html/cart.html
- client/js/cart/jm.js
냉장식품 부분만 구현, 다른 식품에는 장바구니 목록 기능 완성후 추가 예정
화살표 클릭 시 장바구니 목록 생성, 다시 클릭시 닫힘
현재 냉장식품만 구현했는데 장바구니 안의 요소 만든 후 나머지 식품도 추가 예정
6시간
querySelectorAll 을 이용해서 같은 클래스인 모든 버튼에 이벤트를 부여하려 했는데 잘 되지 않아서 id로 이벤트 부여함.
> [#131] Cart 화살표 클릭 시 장바구니 목록 생성

- client/js/product_detail/seohyun.js
상품 설명, 상세 정보, 후기, 문의 메뉴를 누를 때 마다 해당 메뉴에 맞는 페이지가 보이는 기능
메뉴들을 누를 때 마다 메뉴에 맞는 페이지로 스크롤 이동
4시간
정보 찾는 것이 어려웠습니당.
> [#68] 상품 디테일 밑에 있는 메뉴 클릭 시 의미에 맞는 페이지가 보이는 기능

- client/css/pages/register.css
- client/html/register.html
- client/js/register/woonki.js
- 비밀번호 8자리 이상안되면 에러메시지 나오게 하기
- 비밀번호 일치하면 비밀번호 일치 메시지 나오게 하기
- 이메일 유효성 검사 
- 이메일 유효성 검사 맞지 않는다면 이메일 인증 버튼 비활성화 
- 이메일 유효성 검사 일치한다면 인증 버튼 활성화
레이아웃 잡는게 조금 어려웠지만,, 완벽하진 않아도 잡았습니다.
3시간
비밀번호 일치하면 글자색상을 변경하고싶었지만 처음에 잘 되지 않았습니다. 하지만 조건 순서를 바꾸어 성공했습니다.
> [#57, #58] 회원가입_이메일 인증 버튼 구현, 회원가입_비밀번호, 비밀번호 확인

- client/html/register.html
- client/js/register/woonki.js
- 비밀번호 일치
- 이메일 유효성 검사 일치
- 2개 조건 맞아야 가입하기 버튼 구현 완료
- 안 맞으면 버튼 비활성화 맞으면 활성화 작업 완료
원래 짜여있던걸 가져와서 비교만 하면 되는거였습니다.!
20분
조건이 계속 안 맞는 느낌이 들었지만 끝내 수정 완료 하였습니다.!
> [#63] 회원가입 버튼 기능 추가

- client/css/components/header.css
- padding -> display flex / gap 으로 수정
- a 태그 inline block 로 수정
safari 크로스 브라우징 문제 
2시간
> [#104] header - member 요소 CSS 리팩토링

- client/css/pages/register.css
- client/html/register.html
- client/js/register/woonki.js
- 가입하기 누를 시 id, pw 값 로컬스토리지에 보내기
- 가입하기 버튼 누를 시 조건에 맞다면 아이디,비밀번호 값을 로컬스토리지에 올리기
로컬스토리지에 값을 보내는 법을 알았으니,,서버연결 도전 하겠습니다.
1시간,,?
아직 서버를 연결하지 못했지만,,로컬스토리지를 잘 몰라서 어려웠습니다.
> [feat] ID, PW 로컬스토리지에 보내기

- client/css/pages/product-detail.css
- client/html/product-detail.html
- client/js/product_detail/seohyun.js
- 팝업 창 구현 중 : 버튼 디자인 해야 함
- 후기 작성하기 팝업 창 구현 중
- 총 상품 금액 콤마 찍히게 하기
- 크로싱이슈,,width 제거
- .hidden css 추가
진행 중
팝업 방법과 팝업 창 구현을 생각하는 것이 어려웠습니다.
> [#69] 후기 작성하기 누르면 팝업 창 띄우는 기능 구현 중 

- client/css/pages/cart.css
- client/html/cart.html
- client/js/cart/jm.js
- client/js/login/jm.js
+- 버튼 클릭 시 숫자 증가
+- 버튼 클릭 시 숫자 증가할 때 '원'과 숫자가 겹쳐져서 고민중
전체선택 기능 구현중
login과 cart 자스 선언 let으로 변경 
10시간
+버튼으로 금액이 늘어나면 '원'과 겹쳐져서 두칸으로 나눠서 margin, padding, 박스 사이즈, gap, span div추가 등을 해서 css를 바꿔봤는데 잘 안돼서 자바스크립트에 '원'을 추가해봤는데 버튼을 누르기 전 상태에 '원'과 버튼을 눌러 추가된 '원'이 겹쳐서 일단 두칸으로 나눠서 고민중입니다.
전체선택 기능 구현중: 전체선택 checker1 하나가 체크되면 이벤트가 생기는건 성공했는데 checker1이 체크되었을 때 나머지 checker들이 선택되고 checked 상태로 바뀌는걸 모르겠습니다.
> [#143] +- 버튼 클릭 시 숫자 증가

- client/css/pages/main.css
- client/js/main/mkk.js
POPUP AD 오늘하루 안 보기 기능 구현
스토리지를 이용하여 해당 시간동안 팝업창이 다시 뜨지 않도록 하는 기능
2시간
스토리지를 생성하여 하루동안 안보기 기능이 적용이 되었는데도, 새로고침을 누르면 popup 창이 깜빡이면서 사라지는 현상이 발생했다.
브라우저가 렌더링될 때 CSS의 설정대로 팝업창을 불러오고 다시 스토리지를 확인하여 팝업창을 닫는 과정을 거치기 때문에 이러한 현상이 일어났던 것 같다.
이런 현상을 해결하기 위해 CSS 속성값을 display none 으로 지정해두었다.
> [#75] POPUP AD 오늘하루 안 보기 기능 구현

- client/html/register.html
- client/js/register/woonki.js
- unique id , id ,pw 조건 맞을 시 가입하기 버튼 누르면 서버로 전송
- unique id 랜덤 생성
- 가입하기 완료 되면 메인페이지로 이동
서버를 제가 만들진 않았지만,,구글링과 조언을 통하여 성공하니 기쁩니다.!
2월7일 ~ 2월 8일
id,pw value 값이 제대로 받아지지 않아서,,힘들었습니다 ㅜㅜ
> [#182] 가입하기 버튼, 서버연동

- client/css/pages/cart.css
- client/html/cart.html
- client/js/cart/jm.js
- npm start로 실행 시 체크박스 안뜨는 오류 고침
- +-버튼 클릭시 '원'과 겹쳐서 보이는 현상 고침
- x버튼 클릭 시 장바구니에서 사라짐
- 계산기 기능 구현
오류 고치고, 계산기 기능도 한번 넣어봤습니다.
6시간
npm 오류- 백그라운드 이미지를 상대경로로 바꿔서 해결했습니다.
> [#143 #146 #133] +-버튼, x버튼, 계산기 기능 추가

- client/assets/icons/Icon/detail-popup-cancel.svg
- client/css/pages/product-detail.css
- client/html/product-detail.html
- client/js/product_detail/seohyun.js
- client/lib/dom/css.js
- 후기 버튼 누르면 후기 팝업이 뜨고 x와 취소 버튼으로 후기 팝업 끄기 구현
- 문의 버튼 누르면 문의 팝업이 뜨고 x와 취소 버튼으로 문의 팝업 끄기 구현
- 팝업 창 안에서 스크롤 구현
- 정보 밑 메뉴 누를 때 색상 변경 기능 추가
후기와 문의 팝업 기능 추가
하루 반
여러 줄의 안내 문구 기능을 어떻게 구현해야 할지 고민이 많아서 힘들었습니다.
> [#69, #73] 후기 팝업, 문의 팝업 기능 추가 
